### ISSUE TITLE
Separate tests and test fixtures from main code

### ISSUE THREAD

**Issue by timpalpant** [timpalpant/LittleBoxes#16]
Move the tests into a separate directory like `tests/` and make some small test fixtures for ClueDB, Dictionary, etc. in `tests/fixtures` so that the tests run quickly.

**Comment by jpalpant** [comment]
Merged #17, looks good!  Nice to not have to wait ages for the ClueDB to load every time just to run some tests, I always get annoyed when unit testing takes 20 minutes for a handful of tests but didn't know how to make it faster.
