### ISSUE TITLE
Test fixture puzzle not empty

### ISSUE THREAD

**Issue by jpalpant** [timpalpant/LittleBoxes#19]
Running run_tests.sh fails several tests because the puzzle in tests/fixtures/test.puz already has solutions in it.  This means that calling get_fill on that puzzle will not return a list of None values.

**Comment by timpalpant** [comment]
Merged #20 to fix the tests and also set up CircleCI to run the tests automatically for every pull request and commit.

[![Circle CI](https://circleci.com/gh/timpalpant/LittleBoxes.svg?style=svg)](https://circleci.com/gh/timpalpant/LittleBoxes)
